#pragma once

#include "KowaGigEVisionLib.h"
#include <string>

// return: errno
int save_mono_bitmap(const std::string& filename, int height, int width, int width_stride, const char* data);

#define ERRORCODE_CASE(error_macro) case error_macro: return #error_macro
constexpr const char* get_strerror(WORD errorcode) {
    switch (errorcode) {
        // case GEV_STATUS_SUCCESS: return "GEV_STATUS_SUCCESS";
        ERRORCODE_CASE(GEV_STATUS_SUCCESS);
        ERRORCODE_CASE(GEV_STATUS_PACKET_RESEND);
        ERRORCODE_CASE(GEV_STATUS_NOT_IMPLEMENTED);
        ERRORCODE_CASE(GEV_STATUS_INVALID_PARAMETER);
        ERRORCODE_CASE(GEV_STATUS_INVALID_ADDRESS);
        ERRORCODE_CASE(GEV_STATUS_WRITE_PROTECT);
        ERRORCODE_CASE(GEV_STATUS_BAD_ALIGNMENT);
        ERRORCODE_CASE(GEV_STATUS_ACCESS_DENIED);
        ERRORCODE_CASE(GEV_STATUS_BUSY);
        ERRORCODE_CASE(GEV_STATUS_LOCAL_PROBLEM);
        ERRORCODE_CASE(GEV_STATUS_MSG_MISMATCH);
        ERRORCODE_CASE(GEV_STATUS_INVALID_PROTOCOL);
        ERRORCODE_CASE(GEV_STATUS_NO_MSG);
        ERRORCODE_CASE(GEV_STATUS_PACKET_UNAVAILABLE);
        ERRORCODE_CASE(GEV_STATUS_DATA_OVERRUN);
        ERRORCODE_CASE(GEV_STATUS_INVALID_HEADER);
        ERRORCODE_CASE(GEV_STATUS_WRONG_CONFIG);
        ERRORCODE_CASE(GEV_STATUS_PACKET_NOT_YET_AVAILABLE);
        ERRORCODE_CASE(GEV_STATUS_PACKET_AND_PREV_REMOVED_FROM_MEMORY);
        ERRORCODE_CASE(GEV_STATUS_PACKET_REMOVED_FROM_MEMORY);
        ERRORCODE_CASE(GEV_STATUS_NO_REF_TIME1);
        ERRORCODE_CASE(GEV_STATUS_PACKET_TEMPORARILY_UNAVAILABLE);
        ERRORCODE_CASE(GEV_STATUS_OVERFLOW);
        ERRORCODE_CASE(GEV_STATUS_ACTION_LATE);
        ERRORCODE_CASE(GEV_STATUS_ERROR);
        ERRORCODE_CASE(GEV_STATUS_CAMERA_NOT_INIT);
        ERRORCODE_CASE(GEV_STATUS_CAMERA_ALWAYS_INIT);
        ERRORCODE_CASE(GEV_STATUS_CANNOT_CREATE_SOCKET);
        ERRORCODE_CASE(GEV_STATUS_SEND_ERROR);
        ERRORCODE_CASE(GEV_STATUS_RECEIVE_ERROR);
        ERRORCODE_CASE(GEV_STATUS_CAMERA_NOT_FOUND);
        ERRORCODE_CASE(GEV_STATUS_CANNOT_ALLOC_MEMORY);
        ERRORCODE_CASE(GEV_STATUS_TIMEOUT);
        ERRORCODE_CASE(GEV_STATUS_SOCKET_ERROR);
        ERRORCODE_CASE(GEV_STATUS_INVALID_ACK);
        ERRORCODE_CASE(GEV_STATUS_CANNOT_START_THREAD);
        ERRORCODE_CASE(GEV_STATUS_CANNOT_SET_SOCKET_OPT);
        ERRORCODE_CASE(GEV_STATUS_CANNOT_OPEN_DRIVER);
        ERRORCODE_CASE(GEV_STATUS_HEARTBEAT_READ_ERROR);
        ERRORCODE_CASE(GEV_STATUS_EVALUATION_EXPIRED);
        ERRORCODE_CASE(GEV_STATUS_GRAB_ERROR);
        ERRORCODE_CASE(GEV_STATUS_DRIVER_READ_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_READ_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_OPEN_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_FEATURE_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_COMMAND_ERROR);
        ERRORCODE_CASE(GEV_STATUS_GAIN_NOT_SUPPORTED);
        ERRORCODE_CASE(GEV_STATUS_EXPOSURE_NOT_SUPPORTED);
        ERRORCODE_CASE(GEV_STATUS_CANNOT_GET_ADAPTER_INFO);
        ERRORCODE_CASE(GEV_STATUS_ERROR_INVALID_HANDLE);
        ERRORCODE_CASE(GEV_STATUS_CLINK_SET_BAUD);
        ERRORCODE_CASE(GEV_STATUS_CLINK_SEND_BUFFER_FULL);
        ERRORCODE_CASE(GEV_STATUS_CLINK_RECEIVE_BUFFER_NO_DATA);
        ERRORCODE_CASE(GEV_STATUS_FEATURE_NOT_AVAILABLE);
        ERRORCODE_CASE(GEV_STATUS_MATH_PARSER_ERROR);
        ERRORCODE_CASE(GEV_STATUS_FEATURE_ITEM_NOT_AVAILABLE);
        ERRORCODE_CASE(GEV_STATUS_NOT_SUPPORTED);
        ERRORCODE_CASE(GEV_STATUS_GET_URL_ERROR);
        ERRORCODE_CASE(GEV_STATUS_READ_XML_MEM_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_SIZE_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_ZIP_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_ROOT_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_FILE_ERROR);
        ERRORCODE_CASE(GEV_STATUS_DIFFERENT_IMAGE_HEADER);
        ERRORCODE_CASE(GEV_STATUS_XML_SCHEMA_ERROR);
        ERRORCODE_CASE(GEV_STATUS_XML_STYLESHEET_ERROR);
        ERRORCODE_CASE(GEV_STATUS_FEATURE_LIST_ERROR);
        ERRORCODE_CASE(GEV_STATUS_ALREADY_OPEN);
        ERRORCODE_CASE(GEV_STATUS_TEST_PACKET_DATA_ERROR);
        ERRORCODE_CASE(GEV_STATUS_FEATURE_NOT_FLOAT);
        ERRORCODE_CASE(GEV_STATUS_FEATURE_NOT_INTEGER);
        ERRORCODE_CASE(GEV_STATUS_XML_DLL_NOT_FOUND);
        ERRORCODE_CASE(GEV_STATUS_XML_NOT_INIT);
        ERRORCODE_CASE(GEV_STATUS_NOT_SAME_SUBNET);
        ERRORCODE_CASE(GEV_STATUS_GET_MANIFEST_TABLE_ERROR);
        ERRORCODE_CASE(GEV_STATUS_DEPRECATED);
        ERRORCODE_CASE(GEV_STATUS_BUFFERS_NOT_INIT);
    default:
        return "Unknown Error";
    }
}
#undef ERRORCODE_CASE
