
q = from(bucket: "ed1f", org: "hot", host:"http://localhost:8086", token:"6cjMwc6PivweUZ_f3RxLpdEL_sW5ZB22shiXwvcabIEja6UaIiHsZHuSUEdyIF9TZ29Npk5XM9ASqRPo8RwRvg==")
  |> range(start: _start, stop: _stop)
  |> filter(fn: (r) => r["_measurement"] == "pump01" or r["_measurement"] == "pump02")
  |> filter(fn: (r) => r["_field"] == "velocity")
  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)
  |> pivot( rowKey: ["_time"], columnKey: ["_field", "_measurement", "no"], valueColumn: "_value")
  |> keep(columns: ["_time", "velocity_pump01_1", "velocity_pump01_2", "velocity_pump02_3", "velocity_pump02_4"])

p = from(bucket: "data", org: "fxl", host:"http://localhost:8086", token:"6cjMwc6PivweUZ_f3RxLpdEL_sW5ZB22shiXwvcabIEja6UaIiHsZHuSUEdyIF9TZ29Npk5XM9ASqRPo8RwRvg==")
  |> range(start: _start, stop: _stop)
  |> filter(fn: (r) => r["_measurement"] == "app")
  |> filter(fn: (r) => r["_field"] == "pressure")
  |> filter(fn: (r) => r["addr"] == "163" or r["addr"] == "162" or r["addr"] == "161" or r["addr"] == "209")
  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)
  |> pivot( rowKey: ["_time"], columnKey: ["_field", "addr"], valueColumn: "_value")
  |> keep(columns: ["_time", "pressure_161", "pressure_162", "pressure_163", "pressure_209"])

T = from(bucket: "data", org: "fxl", host:"http://localhost:8086", token:"6cjMwc6PivweUZ_f3RxLpdEL_sW5ZB22shiXwvcabIEja6UaIiHsZHuSUEdyIF9TZ29Npk5XM9ASqRPo8RwRvg==")
  |> range(start: _start, stop: _stop)
  |> filter(fn: (r) => r["_measurement"] == "app")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["tag"] == "heating")
  |> filter(fn: (r) => r["addr"] == "1" or r["addr"] == "2" or r["addr"] == "3" or r["addr"] == "4" or r["addr"] == "5")  
  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)
  |> pivot( rowKey: ["_time"], columnKey: ["tag", "addr"], valueColumn: "_value")
  |> keep(columns: ["_time", "heating_1", "heating_2", "heating_3", "heating_4", "heating_5"])

join(tables: {t1: join(tables: {t1: q, t2: p}, on: ["_time"]), t2: T}, on: ["_time"])